### ISSUE TITLE
Getting error using spatie/media-library in Backpack V6

### ISSUE THREAD

**Issue by haniramadhan-kkp** [Laravel-Backpack/community-forum#694] opened 2023-10-02 06:53 UTC
I got this error message fopen(/tmp/phpSd49AI): Failed to open stream: No such file or directory.

In protected function setupCreateOperation() I add this

```
CRUD::field('tindaklanjut_files')
            ->label('Tindak Lanjut Files')
            ->type('upload_multiple')
            ->withMedia([
                'collection' => 'tindaklanjut_files', // will pick the collection definition from your model
            ]);
```

I found that is saved with duplicate file attached. Please give me some clue to solve this problem.

Update:

This problem only occur in create action. But in update action, the error doesn't appear. So, temporarily, I only add upload field in edit mode.

**Comment by jorgetwgroup** [comment] 2023-10-03 12:05
Hello @haniramadhan-kkp i check and is look like an error with spatie/media-library
[error 1](https://github.com/spatie/laravel-medialibrary/issues/3016)
[error 2](https://github.com/spatie/laravel-medialibrary/issues/2891)

You can try to follow instructions [here](https://github.com/spatie/laravel-medialibrary/issues/2891) to check if solve your problem.

Cheers.

**Comment by jorgetwgroup** [comment] 2023-10-05 01:00
Hello @haniramadhan-kkp you was able to try solutions in the links I gave you?

Cheers.

**Comment by haniramadhan-kkp** [comment] 2023-10-05 05:35
> Hello @haniramadhan-kkp you was able to try solutions in the links I gave you?
> 
> Cheers.

Not yet, actually I can't find any clear step by step solution. Can you give me some clear solutions?

**Comment by pxpm** [comment] 2023-10-09 12:52
Hello @haniramadhan-kkp, hope you are doing fine.

Help here to try to figure out what could be the issue.

Do you have any additional configuration in the model regarding that collection ? If you do, can you share it ? 

Also, what's the db column type where you are storing those files ? 

Are you casting, or have any mutator/accessor for that column in your model ? 

Using our demo application, are you able to reproduce your issue ? We have an example in the `ProductCrudController` https://github.com/Laravel-Backpack/demo/blob/ad171c9bc3c5c076dc80d613fd6768c6ba6cedaf/app/Http/Controllers/Admin/ProductCrudController.php#L226 but it requires to run the demo locally. 

Let me know,
Cheers

**Comment by jorgetwgroup** [comment] 2023-10-18 12:11
Hello @haniramadhan-kkp

Please let us know if you still continue with the same problem or if it has already been resolved, if the same problem continues, send us the details and actions you have taken so that we can provide support, in case we do not receive news from you we will close the issue but you are free to open it again whenever you see fit.

Thank you.

**Comment by jorgetwgroup** [comment] 2023-10-19 12:16
Hello @haniramadhan-kkp, we will close this case due to non-activity, if you need it you can reopen it or if it is a different topic, generate a new one.

Cheers

**Closed by jorgetwgroup** 2023-10-19 12:16 UTC
