### ISSUE TITLE
Trigger events in CrudController when operations are set up

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#363] opened 2023-01-13 13:09 UTC
To be able to do things after ALL operations have been setup, and give other types of granular control to the developer, we should maybe trigger events at different points in the CrudController lifecycle:

```php
<?php

use ListOperation; // list
use CreateOperation; // create
use UpdateOperation; // update
use TrashOperation; // list
use ArhiveOperation; // list

CrudController Lifecycle:
// beforeDefaults
- setupDefaults()
    // beforeListOperationDefaults
    // afterListOperationDefaults
  // beforeSetup
- setup()
  // afterSetup
  // beforeListOperationSetup
- setupXOperation()
  // afterListOperationSetup
// everythingIsSetup
```

**Comment by pxpm** [comment] 2024-10-03 14:46
closing, duplicate of: https://github.com/Laravel-Backpack/community-forum/issues/416

**Closed by pxpm** 2024-10-03 14:46 UTC
Labels: Priority: SHOULD
