### ISSUE TITLE
Editable select custom validation message is not showing 

### ISSUE THREAD

**Issue by blessen131** [Laravel-Backpack/community-forum#1229] opened 2024-11-15 16:25 UTC
StatusRequest

` public function rules()
    {
        return [
            'status' => 'in:No Show,Completed',
        ];
    }
    public function attributes()
    {
        return [
            'status' =>'Status'
        ];
    }
    public function messages()
    {
        return [
            'status.in' => 'Not allowed to update other status'
        ];
    }`

Controller
 `protected function setupMinorUpdateOperation()
    {
        $this->crud->setValidation(StatusRequest::class);
    }`

backpack: 5.x

**Comment by blessen131** [comment] 2024-11-18 18:38
I tried all these, still not showing the custom validation message

**Comment by pxpm** [comment] 2024-11-19 12:13
Hello @blessen131 since you said you are using backpack 5x, I assume your editable-columns are 2x. 

I wasn't able to reproduce your issue in backpack 6x with editable-columns 3x (latest version). 

![image](https://github.com/user-attachments/assets/4f1493af-bc70-46bf-b952-917a55d7b74e)

You can check it out at our demo: https://github.com/Laravel-Backpack/demo/blob/41681217933e4dbffa3d0ff282595f3b8c5c7b16/app/Http/Controllers/Admin/EditableMonsterCrudController.php#L88 by changing `text.required` message in `MonsterRequest`. 

https://demo.backpackforlaravel.com/admin/editable-monster

Unfortunately we will not be providing any more bug fixes to 5x branches unless security related issues. 

I am going to close this as I think there isn't nothing we can do here, if you can upgrade your versions you should have the issue fixed. If that's not the case, let us know 👍 

Cheers

**Closed by pxpm** 2024-11-19 12:13 UTC
Labels: triage
